config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :projects do
    resources :lists do
      resources :tasks do
      end
    end
  end

  resources :users
  resources :teams
  resources :sections

  root to: 'users#show'

end

app/models/task.rb
class Task < ApplicationRecord

	belongs_to :project
	belongs_to :section, optional: true
	belongs_to :list
	belongs_to :owner	 , class_name: 'User'

	has_many :notifications, as: :object
	has_many :comments		 , as: :object

	has_and_belongs_to_many :developers, class_name: 'User'

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_depends
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.owner = current_user
    respond_to do |format|
      if @task.save
        format.html { redirect_to @project, notice: "Task was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      puts task_params
      puts "-----------------------------------"
      if params[:add_dev]
        @task.developer_ids = @task.developer_ids << params[:developer_id]
        return
      end

      if @task.update(task_params)
        format.html { redirect_to @project, notice: "Task was successfully updated." }
        format.json { render json: {msg: "Task was successfully updated."}}
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: {msg: "Error: bad parameters"}, status: 400}
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def task_params
      if params[:to_list]
        params.permit(:list_id)
      elsif params[:add_dev]
        params.permit(:developer_id)
      else
        params.require(:task).permit(:title, :description, :data_end, :hours, :position, :state, :project_id, :list_id, :section_id, developer_ids: [])
      end  
    end

    def set_depends
      @project = Project.find(params[:project_id])
      @list = @project.lists.find(params[:list_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = @list.tasks.find(params[:id]) unless params[:to_list]
      @task = Task.find(params[:id]) if params[:to_list]
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: [project, list, task], local: true ) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :project_id, value: project.id %>
  <%= form.hidden_field :list_id, value: list.id %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :data_end %>
    <%= form.date_field :data_end %>
  </div>

  <div class="field">
    <%= form.label :hours %>
    <%= form.number_field :hours %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>
  
  <div class="field">
    <%= form.label :section %>
    <%= collection_select(:task, :section_id, Section.all, :id, :title,) %>
  </div>

  <div class="field">
    <%= link_to "Add", '#', id: 'add_user'%>
  </div>
  <div id="user_conteiner">
    <%= form.label :developers %>
    <div class="field user_main" style="margin: 10px;">
      <%= form.collection_select :'developer_ids[]', project.team.users, :id, :name, {}, { class: 'user_select'} %>
      <%= link_to 'Delete', '#', class: 'delete_user' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :developers %>
    <%= form.collection_select(:developer_ids, project.team.users, :id, :name,{}, {multiple: true})
    %>
  </div>

  <div class="field">
    <%= form.label :developers %>
    <%= form.collection_check_boxes(:developer_ids, project.team.users, :id, :name) %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class='card task-block in_section_<%= task.section.id if task.section %>' style='width: 18rem; margin: 10px; z-index: 0' task_id='<%= task.id %>' >
  <div class="card-header">
    <div style='float: left'>
    		<h5 class='card-title' style='font-size: 20px'> <%= task.title %> </h5>
    	</div>
    	<div style='float: right'>
    		<small class="text-muted"> <%= task.section.title if task.section %> </small> 
    	</div>
  </div>	
  <div  class='card-body'>
  	<p><small class="text-muted"> Date of completion: <%= task.data_end.strftime('%d %b %Y') %> </small> </p>
   	<h6 class='card-subtitle mb-2 text-muted'> <%= task.state %> </h6>
   	<p  class='card-text' style='font-size: 16px'> <%= task.description %> </p>

    <%= link_to( 'Back'  , project_path(task.project), class: 'btn btn-primary') %>
    <%= link_to( 'Edit'  , edit_project_list_task_path(project_id: task.project.id, list_id: task.list.id, id: task.id), class: 'btn btn-info') %>
		<%= link_to( 'Delete', project_list_task_path(project_id: task.project.id, list_id: task.list.id, id: task.id), method: :delete, class: 'btn btn-danger') %>

  </div>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task, project: @project, list: @list %>

<%= link_to 'Back', project_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Data end</th>
      <th>Hours</th>
      <th>Position</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.data_end %></td>
        <td><%= task.hours %></td>
        <td><%= task.position %></td>
        <td><%= task.state %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task, project: @project, list: @list %>

app/views/tasks/show.html.erb
<%= render partial: 'tasks/task', locals: {task: @task} %>