config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :projects do
    resources :lists do
      resources :tasks do
      end
    end
  end

  resources :users
  resources :teams
  resources :sections

  root to: 'users#show'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_and_belongs_to_many :teams

  has_many :notifications
  has_many :comments
  has_many :tasks, foreign_key: :owner_id
  has_many :projects, through: :teams

  has_and_belongs_to_many :jobs, class_name: 'Task'

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: [:new, :create]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
		@user     = current_user
		@teams    = @user.teams
		@projects = @user.projects
	end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
     def set_user
      
      @user = current_user unless params[:id]
      @user ||= User.find(params[:id])

    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :role, :email, :telegram, :active)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role %>
  </div>

  <div class="field">
    <%= form.label :telegram %>
    <%= form.text_field :telegram %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.text_field :active %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Email</th>
      <th>Telegram</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.role %></td>
        <td><%= user.email %></td>
        <td><%= "-" %></td>
        <td><%= user.active %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', user_path %>

app/views/users/show.html.erb
<style>
#email{
  color:green;
}
.field{
  font-style: bold;
}
</style>

<p id="notice"><%= notice %></p>

<p>
  <% parking_spases.each do |parking_spase|%>
    <button class="parking_button" parking_id="<%= parking_spase.id%>">Parking button</button>
    <strong id='parking_template_<%= parking_spase.id %>' class="parking_template">Tempalete data</strong>    
  <% end %>
</p>
<script type="text/javascript">
  $(document).ready(->(){
    $('.parking_template').hide()
  })
  
  $('.parking_button').click(-> (){
    parking_id = $(this).attr('parking_id')
    $('.parking_template').hide()
    $('#parking_template_'+parking_id).show()
  })
</script>


<strong >Email:</strong>
<%= @user.email %>

<p>
  <strong class="parking_template">Teams:</strong>
  <% @teams.each do |team| %>
  	<%= team.title %>
  	<p>
  		<strong>Projects:</strong>
  		<ul>
	  		<% @projects.where(team_id: team.id).each do |project| %>
	  			<li><%= link_to project.title, project_path(project) %></li>
	  		<% end %>
  		</ul>
  	</p>	
  <% end %>
</p>