config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :projects do
    resources :lists do
      resources :tasks do
      end
    end
  end

  resources :users
  resources :teams
  resources :sections

  root to: 'users#show'

end

app/models/project.rb
class Project < ApplicationRecord

	belongs_to :team

	has_many :lists
	has_many :tasks


  # add lat lng by migration
  acts_as_mappable default_units: :kms
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    # {query: "Parking on central str.", lat: 35.876541. lng: -121.35464}
    @projects = ProjectsSearchQuery.new(search_params).call
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @projects.to_json}
    end
  end

  # GET /projects/1 or /projects/1.json
  def show
    @lists    = @project.lists.sort_by {|list| list.position}
    @sections = Section.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, noice: "Project was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :desctiption, :link_to_site, :link_to_manual, :state)
    end

    def search_params
      params.permit(:query, :lat, :lng, :page, :per_page)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :desctiption %>
    <%= form.text_area :desctiption %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :link_to_site %>
    <%= form.text_field :link_to_site %>
  </div>

  <div class="field">
    <%= form.label :link_to_manual %>
    <%= form.text_field :link_to_manual %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>State</th>
      <th>Link to site</th>
      <th>Link to manual</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.desctiption %></td>
        <td><%= project.state %></td>
        <td><%= project.link_to_site %></td>
        <td><%= project.link_to_manual %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', project_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>


<div id="project-block" project_id="<%= @project.id %>">
  <div>
    <p>
      <strong>Title:</strong>
      <%= @project.title %>
      -
      <strong>State:</strong>
      <%= @project.state %>
    </p>
  </div>

  <div class="form-check">
  
    <p>
      <% @sections.each do |section| %>
        
        <%= check_box_tag(:sections, section.id, true, class: 'form-check-input section-point') %>
        <%= label_tag(section.id, section.title, class: 'form-check-label', style: 'margin-right: 20px') %>

      <% end %>
    </p>
    <p>
<!--      <%=
          #collection_check_boxes :section_id, Section.all, :id, :title
      %>
-->
    </p>

  </div>

  <% @lists.each do |list| %>
    <div class="card bg-light mb-3 list-block" style="float: left; width: 24%; margin: 5px; min-height: 40vw; z-index: -100; height: auto" list_id="<%= list.id %>">
      <div class="card-header"> 
        <div style="float: left; width: 100px">
          <%= list.title %>
        </div>
        <div style="float: right; width: 50px">
          <%= link_to "+", new_project_list_task_path(project_id: @project.id,list_id: list.id)%>
        </div> 
      </div>
      
      <div class="card-body" style='z-index: -100'>

        <% list.tasks.each do |task| %>
          <p class="card-text">

            <%= render partial: 'tasks/task', locals: {task: task} %>  

          </p>  
        <% end %>
      </div>
    </div>
  <% end %>

</div>